# Goal run the pipeline in proper order

name: DevSecOps

on:
    push:
        branches:
            - main

jobs:
    code-quality:
        uses: ./.github/workflows/code_set.yml

    secret-scanning:
        needs: code-quality
        uses: ./.github/workflows/secret_scanning.yml